remote_theme: "mmistakes/minimal-mistakes@4.20.2"

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

title: "gentledev10's blog"
subtitle: "Developer blog"

name: &name "Jaemin Seo"
description: "Blog for developers"
logo: "/assets/images/site-logo.png"

search: true
search_full_content: true

author:
  name     : *name
  avatar   : "/assets/images/author-photo.jpg"
  bio      : "Software engineer"
  location : "Republic of Korea"
  links    :
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
      url  : "https://github.com/gentledev10"
    - label: "Linkedin"
      icon : "fab fa-fw fa-linkedin"
      url  : "https://www.linkedin.com/in/jaemin-seo-82799a165/"
    - label: "Email"
      icon : "far fa-fw fa-envelope"
      url  : mailto:86sjmjm@gmail.com

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true

comments:
  provider : "disqus"
  disqus:
    shortname: "gentledev10-github-io"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-8E7R4NHXY7"
    anonymize_ip: false # default

# SEO Related
google_site_verification: "psijgDLdFG4PmfBm6B0OvmChuR6a_m-5m9hozooECJQ"
naver_site_verification: "baca2230ee227e1fbbddf53a4d440a0181d610b6"
